//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int ID { get; set; }
        public string EnglishName { get; set; }
        public string KoreanName { get; set; }
        public string Alias { get; set; }
        public string Player { get; set; }
        public string Group { get; set; }
        public string Explanation { get; set; }
        public string SoundClipLocation { get; set; }
        public string VideoClipLocation { get; set; }
        public string PhotoLocation { get; set; }
        public string Remarks { get; set; }
    }
}
