//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrchestraDBEntities : DbContext
    {
        public OrchestraDBEntities()
            : base("name=OrchestraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<Orchestra> Orchestras { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Bulletin> Bulletins { get; set; }
        public virtual DbSet<ChildCommentTable> ChildCommentTables { get; set; }
        public virtual DbSet<ParentCommentTable> ParentCommentTables { get; set; }
        public virtual DbSet<Artist_Instrument> Artist_Instrument { get; set; }
        public virtual DbSet<Orchestra_Instrument_Artist> Orchestra_Instrument_Artist { get; set; }
    }
}
