//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orchestra
    {
        public int ID { get; set; }
        public string OfficialName { get; set; }
        public string Alias { get; set; }
        public string URL { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string TelNO { get; set; }
        public string FaxNo { get; set; }
        public string ConductorName { get; set; }
        public Nullable<int> Since { get; set; }
    }
}
