//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orchestra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orchestra()
        {
            this.Orchestra_Instrument_Artist = new HashSet<Orchestra_Instrument_Artist>();
            this.PerformanceDetails = new HashSet<PerformanceDetail>();
            this.Performances = new HashSet<Performance>();
        }
    
        public int ID { get; set; }
        public string OfficialName { get; set; }
        public string Alias { get; set; }
        public string URL { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string TelNO { get; set; }
        public string FaxNo { get; set; }
        public string ConductorName { get; set; }
        public Nullable<int> Since { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orchestra_Instrument_Artist> Orchestra_Instrument_Artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceDetail> PerformanceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Performance> Performances { get; set; }
        public virtual UserCommonTable UserCommonTable { get; set; }
    }
}
