//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceDetail
    {
        public int ID { get; set; }
        public Nullable<int> PerformanceID { get; set; }
        public string Title { get; set; }
        public string Orchestra { get; set; }
        public string Instrument { get; set; }
        public string Conductor { get; set; }
        public string Player { get; set; }
        public string Composer { get; set; }
    
        public virtual Performance Performance { get; set; }
    }
}
