//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Performance()
        {
            this.PerformanceDetails = new HashSet<PerformanceDetail>();
            this.PerformanceParentCommentTables = new HashSet<PerformanceParentCommentTable>();
        }
    
        public int ID { get; set; }
        public string PerformanceTitle { get; set; }
        public string Location { get; set; }
        public string ConcertHall { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> OrchestraID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PhotoAddLocation { get; set; }
        public string VideoLocation { get; set; }
        public string TicketBox { get; set; }
        public string PerformanceHour { get; set; }
        public string OrganizerInfo { get; set; }
        public Nullable<bool> Archive { get; set; }
        public string Brochure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceDetail> PerformanceDetails { get; set; }
        public virtual UserCommonTable UserCommonTable { get; set; }
        public virtual Orchestra Orchestra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceParentCommentTable> PerformanceParentCommentTables { get; set; }
    }
}
