//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPersonalInfo
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Affiliation { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string FacebookAddress { get; set; }
        public string TwitterAddress { get; set; }
        public string KakaoTalkAddress { get; set; }
        public string MajorInstrument1 { get; set; }
        public string MajorInstrument2 { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string ProfilePage { get; set; }
        public string Repertory { get; set; }
        public string EndorsorEmailID1 { get; set; }
        public string EndorsorName1 { get; set; }
        public string EndorsorComments1 { get; set; }
        public string EndorsorEmailID2 { get; set; }
        public string EndorsorName2 { get; set; }
        public string EndorsorComments2 { get; set; }
        public string EndorsorEmailID3 { get; set; }
        public string EndorsorName3 { get; set; }
        public string EndorsorComments3 { get; set; }
        public string EndorsorEmailID4 { get; set; }
        public string EndorsorName4 { get; set; }
        public string EndorsorComments4 { get; set; }
        public string EndorsorEmailID5 { get; set; }
        public string EndorsorName5 { get; set; }
        public string EndorsorComments5 { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    
        public virtual UserCommonTable UserCommonTable { get; set; }
    }
}
