//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string EnglishName { get; set; }
        public string KoreanName { get; set; }
        public string UserID { get; set; }
        public string Email { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
    }
}
